### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by carsonfarmer** [ipld/js-dag-json#23]
There are multiple PRs from dependabot to update various underlying deps. Some of these (I'm looking at you cids) are pretty old and leading to some annoying bundling behaviour when combined with other more recent versions required by other IPFS projects. Any chance we could merge some of these version bumps?

cc @mikeal

**Comment by mikeal** [comment]
upgraded all deps to latest and released v2.0.8

**Comment by carsonfarmer** [comment]
Woot woot!
