### ISSUE TITLE
Update for compatibility with multiformats 4 configuration-free API

### ISSUE THREAD

**Issue by andymatuschak** [ipld/js-dag-json#27]
https://github.com/multiformats/js-multiformats/pull/36 rewrites the API of `multiformats` to avoid creating a central registrar object, but this module expects the now-defunct object as an argument to its constructor. This module will need to be rewritten either to import its own dependencies from `multiformats` or to consume them as arguments.

**Comment by rvagg** [comment]
Yep, should be a fairly quick job for someone. I've _nearly_ done it myself over the last few days. Mikeal just did dag-cbor, the new dag-pb is done, this is the next piece of the puzzle.
