### ISSUE TITLE
Bigint support.

### ISSUE THREAD

**Issue by delaneyj** [ipld/js-dag-json#77]
Jason supports arbitrarily sized integers. Would it be possible to support over 2^53-1 values by using bigint?  I'd like to match the snowflake IDs that I'm generating on a back end. Since it uses the full 64 bits it's a real pain in JavaScript

**Comment by rvagg** [comment]
yep https://github.com/ipld/js-dag-json/blob/30578b4f3dc7f2d3b1517ba69965115d17d74e16/test/test-basics.js#L83

**Comment by delaneyj** [comment]
Maybe add to the example so it's clearer.
